rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
     path('', views.index, name='index'),
     path('about/', views.about, name='about'),
     path('category/<slug:category_name_slug>/', 
          views.show_category, name = "show_category"),
     path('add_category/', views.add_category, name = "add_category"),
     path('category/<slug:category_name_slug>/add_page/', 
          views.add_page, name = "add_page"),
     path('restricted/', views.restricted, name='restricted'),
]

rango_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Categories"
    
    def __str__(self):
        return(self.name)

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return(self.title)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Category, Page, UserProfile
from django.contrib.auth.models import User
import re

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text='Please enter the category name.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        # Strip away any leading http or https
        url = re.sub(r"http[s]:[\/]+", "", url)

        # If url is not empty and doesn't start with 'https://',
        # then prepend 'https://' as we want to make sure
        # we are accessing a secure site
        if url:
            url = f'https://{url}'
            cleaned_data['url'] = url

        return cleaned_data
    
    class Meta:
        model = Page
        exclude = ('category',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['aboldmessage'] ='Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    visitor_cookie_handler(request)
    return render(request, 'rango/index.html', context=context_dict)

def about(request):
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = get_server_side_cookie(request, 'visits', 1)
    return render(request, 'rango/about.html', context_dict)

def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['category'] = category
        context_dict['pages'] = pages
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return(redirect(reverse('rango:index')))
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    if category is None:
        redirect(reverse('rango:index'))

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category',
                                        kwargs={"category_name_slug": category_name_slug}))
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).days > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits

rango/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <h1>About</h1>
    <div>
        This tutorial has been put together by Thomas Sandmann <br/>
        Visits: {{ visits }}
    </div>
    <div>
        <img src="{% static 'images/rango.jpg' %}"
             alt="Picture of Rango" width="200"/>
     </div>
     <div>
        <img src="{% get_media_prefix %}cat.jpg" 
             alt = "Picture of a cat" width="200"/>
     </div>
{% endblock %}

rango/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load static %}
{% block body_block %}
    <h1>Add a Category</h1>
    <div>
        <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{hidden}}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }} </br>
            {% endfor %}
            <input type="submit" name="Submit" value="Create Category">
        </form>
    </div>
{% endblock %}

rango/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load static %}
{% block body_block %}
    {% if category %}
        <h1>Add a Page to {{ category.name }}</h1>
        <div>
            <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }} </br>
                {% endfor %}
                <input type="submit" name="Submit" value="Create Page">
            </form>
        </div>
    {% else %}
        Unknown category
    {% endif %}
{% endblock %}

rango/templates/rango/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}
<html>
    <head len="en">
        <meta charset="UTF-8" />
        <title>
            Rango - 
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
            This is body_block's default content.
        {% endblock %}
        </div>
        <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'rango:add_category' %}">Add a new Category</a></li>
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li>
                    <form>
                        {% csrf_token %}
                        <button formaction="{% url 'auth_logout' %}?next={% url 'rango:index' %}" formmethod="post" 
                        type="submit">Logout</button>
                      </form>
                </li>
                {% else %}
                <li><a href="{% url 'registration_register' %}">Sign up</a></li>
                <li>
                    <form>
                        {% csrf_token %}
                        <button formaction="{% url 'auth_login' %}" formmethod="post" 
                        type="submit">Login</button>
                      </form>
                </li>
                 {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

rango/templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
                <li>
                    <strong>
                        <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                    </strong>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

rango/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
            </ul> 
        {% else %}
            <strong> No Pages currently in the Category. </strong>
        {% endif %}
 
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a><br/>
 
    {% else %}
        The specified category does not exist.
    {% endif %}
{% endblock %}

rango/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
    <div>
        {% if user.is_authenticated %}
            howdy {{ user.username }}!
        {% else %}
            hey there partner!
        {% endif %}
    </div>
    <div>
        {% if categories %}
        <h2>Most liked categories</h2>
        <ul>
            {% for category in categories %}
            <li>
                <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>There are no categories present.</strong>
        {% endif %}
    </div>
    <div>
        {% if pages %}
        <h2>Most viewed pages</h2>
        <ul>
            {% for page in pages %}
            <li>
                <a href="{{ page.url }}">{{ page.title }}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>There are no pages present.</strong>
        {% endif %}
    </div>
    <div>
        <a href="{% url 'rango:about' %}">About</a> <br/>
        <a href="{% url 'rango:add_category' %}">Add a New Category</a><br/>
        <img src="{% static 'images/rango.jpg' %}"
        alt="Picture of Rango"/>
    </div>
{% endblock %}

rango/templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load static %}
{% block title_block %}
    Restricted Page
{% endblock %}
{% block body_block %}
    Because you are logged in, you can see this page.
{% endblock%}